### ISSUE TITLE
undefined method `parent_name' for ProjectName::Application:Class (NoMethodError)

### ISSUE THREAD

**Issue by ror-webExpert** [solidusio-contrib/solidus_searchkick#19]
I override all backend apps with view controller and model.  I want to install the searchkick_solidus gem in that app.

I installed both gems:
`gem 'searchkick'
gem 'solidus_searchkick'`
when I run this command "bundle exec rails g solidus_searchkick:install" I got this error.

`in `method_missing': undefined method `parent_name' for ProjectName::Application:Class (NoMethodError)`

I follow the same step this issue ( https://github.com/solidusio-contrib/solidus_searchkick/issues/14)

but when I run the server then 

`/home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/railtie.rb:209:in `method_missing': undefined method `parent_name' for CulturalCandyBackend::Application:Class (NoMethodError)
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/solidus_searchkick-0.3.4/app/models/spree/product_decorator.rb:6:in `block (2 levels) in <main>'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.4/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.4/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.4/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.4/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.4/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.4/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/application/finisher.rb:140:in `block in <module:Finisher>'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `run'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/sajid-ror/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /home/sajid-ror/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/sajid-ror/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/sajid-ror/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/sajid-ror/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /home/sajid-ror/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /home/sajid-ror/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/sajid-ror/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /home/sajid-ror/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/application.rb:391:in `initialize!'
	from /home/sajid-ror/project/CulturalCandyBackend/config/environment.rb:5:in `<main>'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:37:in `start'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:135:in `perform'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/command/base.rb:69:in `perform'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/command.rb:48:in `invoke'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.4/lib/rails/commands.rb:18:in `<main>'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/sajid-ror/project/CulturalCandyBackend/bin/rails:5:in `<top (required)>'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/spring-4.0.0/lib/spring/client/rails.rb:30:in `load'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/spring-4.0.0/lib/spring/client/rails.rb:30:in `call'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/spring-4.0.0/lib/spring/client/command.rb:7:in `call'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/spring-4.0.0/lib/spring/client.rb:30:in `run'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/spring-4.0.0/bin/spring:49:in `<top (required)>'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `load'
	from /home/sajid-ror/.rvm/gems/ruby-3.0.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/sajid-ror/project/CulturalCandyBackend/bin/spring:10:in `require'
	from /home/sajid-ror/project/CulturalCandyBackend/bin/spring:10:in `block in <top (required)>'
	from <internal:kernel>:90:in `tap'
	from /home/sajid-ror/project/CulturalCandyBackend/bin/spring:7:in `<top (required)>'
	from bin/rails:2:in `load'
	from bin/rails:2:in `<main>'
`

**Comment by kennyadsl** [comment]
Hello @ror-webExpert, is this fixed already?
