### ISSUE TITLE
Reference to `currently_valid_prices` breaks this extension in Solidus >= 3.1

### ISSUE THREAD

**Issue by michaelmichael** [solidusio-contrib/solidus_searchkick#21]
As of Solidus 3.1.0, `currently_valid_prices` [has been moved into a method](https://github.com/solidusio/solidus/pull/4073/commits/515fbe501741aa85d4423ddb69edd08dd6a6ea5f). Since this extension references it as an association, the extension is broken on Solidus >= 3.1.0

I believe we can simply change [this line](https://github.com/solidusio-contrib/solidus_searchkick/blob/e4dea38a10c128ca2acb09209447a2f51a664cc0/app/models/spree/search/searchkick.rb#L123) to 
``` ruby
      includes_clause =  { master: [:prices] }
```
And that fixes it—in our specs anyway. I will submit a pull request with that change.

**Comment by kennyadsl** [comment]
Hey @michaelmichael, thanks for the help here. Let me know when the PR is ready for review!
